name: 更新 GitHub 统计卡片
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# 关键：赋予读写权限
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 生成 Stats 卡片
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=wty2019wty&show_icons=true&theme=dark&locale=cn
          path: assets/github-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 生成语言统计卡片
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=wty2019wty&layout=compact&show_icons=true&theme=dark&locale=cn
          path: assets/github-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # 官方自动提交工具，不会403
      - name: 自动提交推送
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update github stats svg
          file_pattern: assets/*.svg
